version: '3.8'

services:
  app:
    build: .
    container_name: imapsync_app
    restart: always
    environment:
      - DB_HOST=global-mariadb
      - DB_USER=root
      - DB_PASSWORD=+_4nw=c7vAHh^gDjf5x?
      - DB_NAME=imapsync_db
      - DB_PORT=3306
      - APP_ENV=production
    networks:
      - web_network
    volumes:
      - ./backend/logs:/app/backend/logs
      # Optional: Map port if you want to test directly via IP:Port before setting up NPM
      # - "8000:8000" 

networks:
  web_network:
    external: true
